ASFLAGS_ADDITIONAL = --float_support=fpu32
CCSINSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/3P778C~1.INS/TIC28X~1.INS/TI-CGT~1.LTS
CCSSCRIPTINGDIR = D:/ccs/ccs_base/SCRIPT~1
CONTROLSUITEINSTALLDIR = C:/ti/CONTRO~1/
C2000WAREINSTALLDIR = D:/ti/C2000W~2
CCSARMINSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/3P778C~1.INS/TIARMC~1.INS/TI-CGT~1.LTS
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2022b/toolbox/target/SUPPOR~1/tic2000
STACK_SIZE = 1024
